INSERT INTO katalog_swiadczen (kod_procedury, nazwa, kategoria, opis) VALUES
('RKO01', 'Resuscytacja krążeniowo-oddechowa (RKO)',    'resuscytacja',     'Uciskanie klatki + wentylacja'),
('INT01', 'Intubacja dotchawicza',                       'wentylacja',       'Zabezpieczenie drożności dróg oddechowych'),
('EKG01', 'EKG 12-odprowadzeniowe',                      'diagnostyka',      'Rejestracja elektrokardiogramu'),
('CIS01', 'Pomiar ciśnienia tętniczego',                 'diagnostyka',      'Ciśnienie metodą osłuchową lub NIBP'),
('OXY01', 'Pulsoksymetria',                              'diagnostyka',      'Pomiar saturacji krwi tlenem'),
('TLE01', 'Tlenoterapia bierna',                         'wentylacja',       'Podanie tlenu przez maskę/wąsy'),
('DEF01', 'Defibrylacja elektryczna',                    'resuscytacja',     'Wyładowanie elektryczne przy VF/VT'),
('GUK01', 'Pomiar glikemii',                             'diagnostyka',      'Glukometr nakłuciowy'),
('WKL01', 'Wkłucie obwodowe (kaniula i.v.)',             'dostęp_naczyniowy','Obwodowy dostęp dożylny'),
('PLY01', 'Podanie płynów infuzyjnych',                  'farmakoterapia',   'NaCl 0.9% lub Ringer i.v.'),
('ADR01', 'Podanie adrenaliny i.v.',                     'farmakoterapia',   'Epinefryna 1 mg/ml i.v.'),
('GLU01', 'Podanie glukozy 40% i.v.',                    'farmakoterapia',   'Leczenie hipoglikemii'),
('NIT01', 'Podanie nitrogliceryny s.l.',                 'farmakoterapia',   'Spray lub tabletka podjęzykowa'),
('MOR01', 'Podanie morfiny i.v.',                        'farmakoterapia',   'Analgezja opioidowa'),
('IMP01', 'Unieruchomienie złamania (szyna/deska)',      'ortopedia',        'Stabilizacja złamania lub skręcenia'),
('OPA01', 'Opatrunek rany',                              'chirurgia',        'Jałowy opatrunek uciskowy'),
('NEB01', 'Nebulizacja leku rozszerzającego oskrzela',   'wentylacja',       'Salbutamol lub bromek ipratropium'),
('USG01', 'USG FAST (uraz)',                             'diagnostyka',      'Szybka ocena jamy brzusznej i klatki'),
('GCS01', 'Ocena stanu świadomości (GCS)',               'diagnostyka',      'Skala Glasgow Coma Scale'),
('ZAB01', 'Zabezpieczenie kręgosłupa (kołnierz + deska)','ortopedia',       'Immobilizacja kręgosłupa szyjnego');
